version: 2.1

orbs:
  rok8s-scripts: fairwinds/rok8s-scripts@10

jobs:
  test:
    docker:
      - image: circleci/golang:1.12-stretch
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0
      - run: go get github.com/gojp/goreportcard/cmd/goreportcard-cli
      - run: make lint
      - run: make test

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /v.*/
      - rok8s-scripts/github_release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
